os:
    - osx

language: 
    - objective-c
    
# http://stackoverflow.com/a/24600210/265791
# Handle git submodules yourself
git:
    submodules: false

# http://stackoverflow.com/a/24600210/265791
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

before_install:
    - echo "before_install - osx"
    
script: 
    - cd src/ && make osx
    
after_success:
    - echo "Success!"

after_failure:
    - echo "Something went wrong..."