os:
    - osx

language: 
    - objective-c

before_install:
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then echo "before_install - osx"; fi
    
script: 
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then cd miniAudicle/src/ && make osx; fi
    
after_success:
    - echo "Success!"

after_failure:
    - echo "Something went wrong..."